export { default as Facebook } from "./Facebook";
export { default as MapPin } from "./MapPin";
export { default as Phone } from "./Phone";
export { default as Mail } from "./Mail";
export { default as Search } from "./Search";
export { default as Bike } from "./Bike";
export { default as Chainset } from "./Chainset";
export { default as Helmet } from "./Helmet";
export { default as Messenger } from "./Messenger";
